### ISSUE TITLE
Sound breaks the game on Bash for Windows

### ISSUE THREAD

**Issue by HunterBrown** [Luxab/oops#17]
Pulseaudio is not supported, and game cannot launch on bash for windows

**Comment by HunterBrown** [comment]
If I comment out all the sound code, it works fine- it is a known issue that audio does not work on Bash for Windows

**Comment by anoadragon453** [comment]
Not sure of any way to identify if the sound libraries are available at compile time.

I'm afraid we'll just have to mark it as unsupported. Does this break your workflow? Can you use a native Linux desktop to compile instead? VM maybe?

**Comment by HunterBrown** [comment]
https://github.com/aseering/wsl_gui_autoinstall
For future reference, follow the instructions here
